### ISSUE TITLE
全局异常

### ISSUE THREAD

**Issue by Edinjohn** [Zoctan/spring-boot-vue-admin#1]
@RestControllerAdvice
全局异常捕捉后直接ResultGenerator.genFailedResult(msg)，返回
api是有返回错误信息，但是后端日志没有记录。。。

**Comment by Zoctan** [comment]
后端没有开日志啊，是说控制台没有记录输出吗？

**Comment by wangkun19831228** [comment]
api启动报错（org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistenceExceptionTranslationPostProcessor' defined in class path resource [org/springframework/boot/autoconfigure/dao/PersistenceExceptionTranslationAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor]: Factory method 'persistenceExceptionTranslationPostProcessor' threw exception; nested exception is java.lang.StackOverflowError
）

**Comment by wangkun19831228** [comment]
@Zoctan 是的，但是jasypt-spring-boot-starter 2.0.0一开始取不到，所以用了1.8，发现1.8有问题，就手工下载了放到本地库里。

**Comment by Zoctan** [comment]
@wangkun19831228 所以问题解决了吗？

**Comment by Edinjohn** [comment]
建议在全局异常捕捉的时候增加，logger.error("xxx",e)
否则异常一直向外抛，被@RestControllerAdvice直接抛到请求返回的地方去了。
比如SQLException，前端那边只收到databases error，后端你这边没写e.printStackTrace() logger.error，就永远不知道哪里错了。

**Comment by Zoctan** [comment]
@Edinjohn 嗯嗯，我全部加上 log 好了

**Comment by Edinjohn** [comment]
另外有2个疑问：
为什么发生exception的时候要直接在HttpStatus返回状态码。。这样的话，发生报错实际上请求成功了，但是返回的是403 400之类，前端以为请求没成功？
设置spring.mvc.throw-exception-if-no-handler-found=true的时候一定要设置spring.resources.add-mappings=false吗？项目中有用到swagger的话，需要用到静态资源，怎么设置才能既把404交给异常处理器处理，又能使用swagger？

**Comment by Zoctan** [comment]
1、4xx的状态是告诉前端，客户端的数据可能存在问题，我之前没仔细看状态码，然后有些属于服务器的写错成了客户端的，其实这里应该是要自己定义一个状态码枚举类的，我没做这一步。
2、这两项并没有冲突吧，我在种子项目里集成了swagger，你可以看看。
