### ISSUE TITLE
在IDE中开发没有问题，但是部署时出现问题

### ISSUE THREAD

**Issue by PZWM** [Zoctan/spring-boot-vue-admin#10]
使用jar部署在初始秘钥的时候会出错

**Comment by Zoctan** [comment]
和密钥的资源路径有关，推荐把密钥的字符串直接写在配置文件里，可以参考后端模板[https://github.com/Zoctan/spring-boot-api-seedling/tree/master/src/main/java/com/zoctan/seedling/core/rsa](rsa工具)
