### ISSUE TITLE
npm 包冲突

### ISSUE THREAD

**Issue by Edinjohn** [Zoctan/spring-boot-vue-admin#11]
npm install
npm run dev 
会提示webpack版本出错。
回退到28 Feb你升级webpack-dev-server版本之前的代码（3.1.11->2.9.1），可以正常运行。
node v10.15.3
npm v6.4.1
我和我的朋友起项目都有这个报错，他的npm版本大概是6.3

**Comment by SZ98** [comment]
原因：这是新版webpack存在的BUG，卸载现有的新版本webpack，装老版本就好。

（1）npm uninstall webpack-dev-server

（2）npm install webpack-dev-server@2.9.1

（3）npm run dev
