### ISSUE TITLE
启动后显示”认证异常“

### ISSUE THREAD

**Issue by l1090865** [Zoctan/spring-boot-vue-admin#17]
显示”认证异常“。新手表示不能解决🤨  ![TIM图片20200405181319](https://user-images.githubusercontent.com/34509254/78472212-a747e680-7769-11ea-847f-9a1cf370b270.png)
下面是我能找到的同时发生的其他问题：
![图片](https://user-images.githubusercontent.com/34509254/78472278-0c034100-776a-11ea-8095-af2ee3722ad2.png)
![图片](https://user-images.githubusercontent.com/34509254/78472296-2806e280-776a-11ea-9bf1-fb743e0c29ad.png)

**Comment by Zoctan** [comment]
api\src\main\java\com\tsbtv\index\core\configWebSecurityConfig.java
需要在这个文件写不需要认证的请求路径，因为默认是所有请求都需要认证。
