### ISSUE TITLE
异常DerInputStream.getLength(): lengthTag=111, too big.

### ISSUE THREAD

**Issue by 233moutian** [Zoctan/spring-boot-vue-admin#2]
你好!我在拉去您的项目后,正常的启动项目后报此错误.一顿调试后发现是加载私钥的方法出了问题:
com.zoctan.api.util.RSAUtil类中replaceAndBase64Decode()方法:
`final byte[] decoded = this.replaceAndBase64Decode(
                    pem,
                    "-----BEGIN PRIVATE KEY-----\n",
                    "-----END PRIVATE KEY-----"
            );`
此代码的headReplace参数无法正常的replace.导致lengthTag过长.希望您能查看一下是否有此问题!
我就先用自己的办法解决了.

**Comment by 233moutian** [comment]
简单粗暴,将那些无用的前置和后置字符串全删了,pem文件中仅保留key字符串.代码中也是同样处理

**Comment by 233moutian** [comment]
`在后期的继续调试中.由于考虑秘钥文件*.pem是直接生成的,去修改它的格式并不合适,由此思考,是否能通过改代码的方式修复此bug.最后定义到问题的点为,头字符串`-----BEGIN PUBLIC KEY-----`和-`----BEGIN PRIVATE KEY-----`无法正常的去除,导致字符串过长,而公钥和私钥的尾字符串都是能正常的去除的.
**这个原因是因为头字符串的换行无法被识别**,如果在你的loadPemPublicKey()和loadPemPrivateKey()方法中去掉换行符,那就没有这个错误,但是这种方式加工出来的秘钥会有换行符,但程序仍然能正常运行!
然后我将最初的版本,即up主原代码弄到linux上运行,发现并没有此问题,那这个问题可能真的是只有部分系统才会出现...
巴拉巴拉一大堆,这个问题大概就是这样了....

**Comment by Zoctan** [comment]
最近很多人问到出现该异常，从上面233的描述来看应该是Windows下才出现的问题，因为我是Linux所以一直没发现有该问题。

**Comment by midobabi** [comment]
windows下的换行符是 \r\n，linux下是\n，改下代码就可以了，如下：
![image](https://user-images.githubusercontent.com/17424075/44321122-bedd3900-a478-11e8-8922-fa6bdd751120.png)
或者修改pem文件，把换行符直接去掉。

**Comment by Zoctan** [comment]
已经修改RSAUtils

**Comment by chjiyun** [comment]
厉害 删除首尾分割字符串就好了
