### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: 'Content-Type' cannot contain wildcard type '*'

### ISSUE THREAD

**Issue by 233moutian** [Zoctan/spring-boot-vue-admin#3]
1. 我在自己新增了一个不需要权限校验的接口后, 例如像对外访问的回调方法. 并且在WebSecurityConfig中配置了允许匿名访问. 但是访问时出现了此异常.
2. 我用maven package时, 会自动运行UserControllerTest测试类中的登录方法,也会报这个异常.
我使用了https://blog.csdn.net/wd2014610/article/details/80861373这个解决办法.
请楼主测试一下是否有此问题.
另外JwtAuthenticationFilter类中,下面这行代码少了一对{}.
`log.info("JwtFilter => Anonymous<> request URL<{}> Method<{}>", IpUtil.getIpAddress(request), request.getRequestURL(), request.getMethod());
`

**Comment by Zoctan** [comment]
1.和链接的解决办法差不多，添加 APPLICATION_JSON_UTF8 等请求类型支持：

```java
converter.setSupportedMediaTypes(new ArrayList<MediaType>() {{
            this.add(MediaType.APPLICATION_JSON_UTF8);
            this.add(MediaType.APPLICATION_FORM_URLENCODED);
            this.add(MediaType.TEXT_HTML);
}});
```

2、自动运行的测试类也是以上原因，maven 打包时可以忽略测试。
3、已加回去。
