### ISSUE TITLE
非bug：前端项目js文件过大

### ISSUE THREAD

**Issue by 233moutian** [Zoctan/spring-boot-vue-admin#5]
![tim 20180817181930](https://user-images.githubusercontent.com/17902862/44261397-1ea1cd00-a24a-11e8-98b4-7fc3ad3cb719.png)
如图，这个大小是我往里面加了不少功能的结果，但是第一次访问的速度比较慢，不知道up主有什么办法优化没有？但是原来的vue-element-admin并没有此问题。

**Comment by Zoctan** [comment]
@233moutian 唔。。这个是vue的问题，你看看这个：[路由懒加载](https://router.vuejs.org/zh/guide/advanced/lazy-loading.html#%E6%8A%8A%E7%BB%84%E4%BB%B6%E6%8C%89%E7%BB%84%E5%88%86%E5%9D%97)
