### ISSUE TITLE
请问楼主，Permission表中的数据从哪里来的

### ISSUE THREAD

**Issue by SmileFacehhh** [Zoctan/spring-boot-vue-admin#7]
![image](https://user-images.githubusercontent.com/34115282/47659131-3d6bfa80-dbcf-11e8-8a6b-bebdb9977b3c.png)

**Comment by Zoctan** [comment]
什么意思？

**Comment by SmileFacehhh** [comment]
permission权限表中的数据，是手动用sql添加的，还是后端代码里有相应的添加逻辑？

**Comment by SmileFacehhh** [comment]
楼主，能根据前端新增的路由，同时后端在permission表中插入数据的逻辑？

**Comment by Zoctan** [comment]
昨天也想了下，即使数据库添加了那些权限信息，但是后端代码的controller注解@hasPermission上还是要手动添加相关的权限，因为这个并不是按路由分配权限的，是按动作分配的，所以目前没有想到什么好办法解决这个。
